#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MVCEmpleado")]
	public partial class POSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCATALOGO(CATALOGO instance);
    partial void UpdateCATALOGO(CATALOGO instance);
    partial void DeleteCATALOGO(CATALOGO instance);
    partial void InsertCONFIG_PROMOCION(CONFIG_PROMOCION instance);
    partial void UpdateCONFIG_PROMOCION(CONFIG_PROMOCION instance);
    partial void DeleteCONFIG_PROMOCION(CONFIG_PROMOCION instance);
    partial void InsertMENU(MENU instance);
    partial void UpdateMENU(MENU instance);
    partial void DeleteMENU(MENU instance);
    partial void InsertPRODUCTO(PRODUCTO instance);
    partial void UpdatePRODUCTO(PRODUCTO instance);
    partial void DeletePRODUCTO(PRODUCTO instance);
    partial void InsertPROMOCION(PROMOCION instance);
    partial void UpdatePROMOCION(PROMOCION instance);
    partial void DeletePROMOCION(PROMOCION instance);
    partial void InsertROL(ROL instance);
    partial void UpdateROL(ROL instance);
    partial void DeleteROL(ROL instance);
    partial void InsertROL_MENU(ROL_MENU instance);
    partial void UpdateROL_MENU(ROL_MENU instance);
    partial void DeleteROL_MENU(ROL_MENU instance);
    partial void InsertTICKET(TICKET instance);
    partial void UpdateTICKET(TICKET instance);
    partial void DeleteTICKET(TICKET instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    #endregion
		
		public POSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MVCEmpleadoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public POSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CATALOGO> CATALOGOs
		{
			get
			{
				return this.GetTable<CATALOGO>();
			}
		}
		
		public System.Data.Linq.Table<CONFIG_PROMOCION> CONFIG_PROMOCIONs
		{
			get
			{
				return this.GetTable<CONFIG_PROMOCION>();
			}
		}
		
		public System.Data.Linq.Table<MENU> MENUs
		{
			get
			{
				return this.GetTable<MENU>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCTO> PRODUCTOs
		{
			get
			{
				return this.GetTable<PRODUCTO>();
			}
		}
		
		public System.Data.Linq.Table<PROMOCION> PROMOCIONs
		{
			get
			{
				return this.GetTable<PROMOCION>();
			}
		}
		
		public System.Data.Linq.Table<ROL> ROLs
		{
			get
			{
				return this.GetTable<ROL>();
			}
		}
		
		public System.Data.Linq.Table<ROL_MENU> ROL_MENUs
		{
			get
			{
				return this.GetTable<ROL_MENU>();
			}
		}
		
		public System.Data.Linq.Table<TICKET> TICKETs
		{
			get
			{
				return this.GetTable<TICKET>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIOs
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CATALOGO")]
	public partial class CATALOGO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCatalogo;
		
		private string _nombre;
		
		private string _descripcion;
		
		private string _Valor;
		
		private int _catalogo1;
		
		private System.Nullable<bool> _subCatalogo;
		
		private bool _activo;
		
		private EntitySet<CATALOGO> _CATALOGOs;
		
		private EntitySet<PRODUCTO> _PRODUCTOs;
		
		private EntityRef<CATALOGO> _CATALOGO2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCatalogoChanging(int value);
    partial void OnidCatalogoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnValorChanging(string value);
    partial void OnValorChanged();
    partial void Oncatalogo1Changing(int value);
    partial void Oncatalogo1Changed();
    partial void OnsubCatalogoChanging(System.Nullable<bool> value);
    partial void OnsubCatalogoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public CATALOGO()
		{
			this._CATALOGOs = new EntitySet<CATALOGO>(new Action<CATALOGO>(this.attach_CATALOGOs), new Action<CATALOGO>(this.detach_CATALOGOs));
			this._PRODUCTOs = new EntitySet<PRODUCTO>(new Action<PRODUCTO>(this.attach_PRODUCTOs), new Action<PRODUCTO>(this.detach_PRODUCTOs));
			this._CATALOGO2 = default(EntityRef<CATALOGO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCatalogo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCatalogo
		{
			get
			{
				return this._idCatalogo;
			}
			set
			{
				if ((this._idCatalogo != value))
				{
					this.OnidCatalogoChanging(value);
					this.SendPropertyChanging();
					this._idCatalogo = value;
					this.SendPropertyChanged("idCatalogo");
					this.OnidCatalogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="catalogo", Storage="_catalogo1", DbType="Int NOT NULL")]
		public int catalogo1
		{
			get
			{
				return this._catalogo1;
			}
			set
			{
				if ((this._catalogo1 != value))
				{
					this.Oncatalogo1Changing(value);
					this.SendPropertyChanging();
					this._catalogo1 = value;
					this.SendPropertyChanged("catalogo1");
					this.Oncatalogo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subCatalogo", DbType="Bit")]
		public System.Nullable<bool> subCatalogo
		{
			get
			{
				return this._subCatalogo;
			}
			set
			{
				if ((this._subCatalogo != value))
				{
					this.OnsubCatalogoChanging(value);
					this.SendPropertyChanging();
					this._subCatalogo = value;
					this.SendPropertyChanged("subCatalogo");
					this.OnsubCatalogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATALOGO_CATALOGO", Storage="_CATALOGOs", ThisKey="idCatalogo", OtherKey="catalogo1")]
		public EntitySet<CATALOGO> CATALOGOs
		{
			get
			{
				return this._CATALOGOs;
			}
			set
			{
				this._CATALOGOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATALOGO_PRODUCTO", Storage="_PRODUCTOs", ThisKey="idCatalogo", OtherKey="tipo")]
		public EntitySet<PRODUCTO> PRODUCTOs
		{
			get
			{
				return this._PRODUCTOs;
			}
			set
			{
				this._PRODUCTOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATALOGO_CATALOGO", Storage="_CATALOGO2", ThisKey="catalogo1", OtherKey="idCatalogo", IsForeignKey=true)]
		public CATALOGO CATALOGO2
		{
			get
			{
				return this._CATALOGO2.Entity;
			}
			set
			{
				CATALOGO previousValue = this._CATALOGO2.Entity;
				if (((previousValue != value) 
							|| (this._CATALOGO2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATALOGO2.Entity = null;
						previousValue.CATALOGOs.Remove(this);
					}
					this._CATALOGO2.Entity = value;
					if ((value != null))
					{
						value.CATALOGOs.Add(this);
						this._catalogo1 = value.idCatalogo;
					}
					else
					{
						this._catalogo1 = default(int);
					}
					this.SendPropertyChanged("CATALOGO2");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CATALOGOs(CATALOGO entity)
		{
			this.SendPropertyChanging();
			entity.CATALOGO2 = this;
		}
		
		private void detach_CATALOGOs(CATALOGO entity)
		{
			this.SendPropertyChanging();
			entity.CATALOGO2 = null;
		}
		
		private void attach_PRODUCTOs(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.CATALOGO = this;
		}
		
		private void detach_PRODUCTOs(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.CATALOGO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONFIG_PROMOCION")]
	public partial class CONFIG_PROMOCION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _producto;
		
		private string _promocion;
		
		private bool _activo;
		
		private EntityRef<PRODUCTO> _PRODUCTO1;
		
		private EntityRef<PROMOCION> _PROMOCION1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductoChanging(int value);
    partial void OnproductoChanged();
    partial void OnpromocionChanging(string value);
    partial void OnpromocionChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public CONFIG_PROMOCION()
		{
			this._PRODUCTO1 = default(EntityRef<PRODUCTO>);
			this._PROMOCION1 = default(EntityRef<PROMOCION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					if (this._PRODUCTO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductoChanging(value);
					this.SendPropertyChanging();
					this._producto = value;
					this.SendPropertyChanged("producto");
					this.OnproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_promocion", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string promocion
		{
			get
			{
				return this._promocion;
			}
			set
			{
				if ((this._promocion != value))
				{
					if (this._PROMOCION1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpromocionChanging(value);
					this.SendPropertyChanging();
					this._promocion = value;
					this.SendPropertyChanged("promocion");
					this.OnpromocionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_CONFIG_PROMOCION", Storage="_PRODUCTO1", ThisKey="producto", OtherKey="idProdcuto", IsForeignKey=true)]
		public PRODUCTO PRODUCTO1
		{
			get
			{
				return this._PRODUCTO1.Entity;
			}
			set
			{
				PRODUCTO previousValue = this._PRODUCTO1.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCTO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCTO1.Entity = null;
						previousValue.CONFIG_PROMOCIONs.Remove(this);
					}
					this._PRODUCTO1.Entity = value;
					if ((value != null))
					{
						value.CONFIG_PROMOCIONs.Add(this);
						this._producto = value.idProdcuto;
					}
					else
					{
						this._producto = default(int);
					}
					this.SendPropertyChanged("PRODUCTO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROMOCION_CONFIG_PROMOCION", Storage="_PROMOCION1", ThisKey="promocion", OtherKey="idPromocion", IsForeignKey=true)]
		public PROMOCION PROMOCION1
		{
			get
			{
				return this._PROMOCION1.Entity;
			}
			set
			{
				PROMOCION previousValue = this._PROMOCION1.Entity;
				if (((previousValue != value) 
							|| (this._PROMOCION1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROMOCION1.Entity = null;
						previousValue.CONFIG_PROMOCIONs.Remove(this);
					}
					this._PROMOCION1.Entity = value;
					if ((value != null))
					{
						value.CONFIG_PROMOCIONs.Add(this);
						this._promocion = value.idPromocion;
					}
					else
					{
						this._promocion = default(string);
					}
					this.SendPropertyChanged("PROMOCION1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MENU")]
	public partial class MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMenu;
		
		private string _pagina;
		
		private string _descripcion;
		
		private System.Nullable<bool> _activo;
		
		private EntitySet<ROL_MENU> _ROL_MENUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMenuChanging(int value);
    partial void OnidMenuChanged();
    partial void OnpaginaChanging(string value);
    partial void OnpaginaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnactivoChanging(System.Nullable<bool> value);
    partial void OnactivoChanged();
    #endregion
		
		public MENU()
		{
			this._ROL_MENUs = new EntitySet<ROL_MENU>(new Action<ROL_MENU>(this.attach_ROL_MENUs), new Action<ROL_MENU>(this.detach_ROL_MENUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMenu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMenu
		{
			get
			{
				return this._idMenu;
			}
			set
			{
				if ((this._idMenu != value))
				{
					this.OnidMenuChanging(value);
					this.SendPropertyChanging();
					this._idMenu = value;
					this.SendPropertyChanged("idMenu");
					this.OnidMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagina", DbType="NVarChar(200)")]
		public string pagina
		{
			get
			{
				return this._pagina;
			}
			set
			{
				if ((this._pagina != value))
				{
					this.OnpaginaChanging(value);
					this.SendPropertyChanging();
					this._pagina = value;
					this.SendPropertyChanged("pagina");
					this.OnpaginaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(200)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit")]
		public System.Nullable<bool> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_ROL_MENU", Storage="_ROL_MENUs", ThisKey="idMenu", OtherKey="menu")]
		public EntitySet<ROL_MENU> ROL_MENUs
		{
			get
			{
				return this._ROL_MENUs;
			}
			set
			{
				this._ROL_MENUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ROL_MENUs(ROL_MENU entity)
		{
			this.SendPropertyChanging();
			entity.MENU1 = this;
		}
		
		private void detach_ROL_MENUs(ROL_MENU entity)
		{
			this.SendPropertyChanging();
			entity.MENU1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTO")]
	public partial class PRODUCTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProdcuto;
		
		private string _producto1;
		
		private int _tipo;
		
		private decimal _precio_venta;
		
		private bool _activo;
		
		private EntitySet<CONFIG_PROMOCION> _CONFIG_PROMOCIONs;
		
		private EntitySet<TICKET> _TICKETs;
		
		private EntityRef<CATALOGO> _CATALOGO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProdcutoChanging(int value);
    partial void OnidProdcutoChanged();
    partial void Onproducto1Changing(string value);
    partial void Onproducto1Changed();
    partial void OntipoChanging(int value);
    partial void OntipoChanged();
    partial void Onprecio_ventaChanging(decimal value);
    partial void Onprecio_ventaChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public PRODUCTO()
		{
			this._CONFIG_PROMOCIONs = new EntitySet<CONFIG_PROMOCION>(new Action<CONFIG_PROMOCION>(this.attach_CONFIG_PROMOCIONs), new Action<CONFIG_PROMOCION>(this.detach_CONFIG_PROMOCIONs));
			this._TICKETs = new EntitySet<TICKET>(new Action<TICKET>(this.attach_TICKETs), new Action<TICKET>(this.detach_TICKETs));
			this._CATALOGO = default(EntityRef<CATALOGO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProdcuto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idProdcuto
		{
			get
			{
				return this._idProdcuto;
			}
			set
			{
				if ((this._idProdcuto != value))
				{
					this.OnidProdcutoChanging(value);
					this.SendPropertyChanging();
					this._idProdcuto = value;
					this.SendPropertyChanged("idProdcuto");
					this.OnidProdcutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="producto", Storage="_producto1", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string producto1
		{
			get
			{
				return this._producto1;
			}
			set
			{
				if ((this._producto1 != value))
				{
					this.Onproducto1Changing(value);
					this.SendPropertyChanging();
					this._producto1 = value;
					this.SendPropertyChanged("producto1");
					this.Onproducto1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Int NOT NULL")]
		public int tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					if (this._CATALOGO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Money NOT NULL")]
		public decimal precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_CONFIG_PROMOCION", Storage="_CONFIG_PROMOCIONs", ThisKey="idProdcuto", OtherKey="producto")]
		public EntitySet<CONFIG_PROMOCION> CONFIG_PROMOCIONs
		{
			get
			{
				return this._CONFIG_PROMOCIONs;
			}
			set
			{
				this._CONFIG_PROMOCIONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_TICKET", Storage="_TICKETs", ThisKey="idProdcuto", OtherKey="producto")]
		public EntitySet<TICKET> TICKETs
		{
			get
			{
				return this._TICKETs;
			}
			set
			{
				this._TICKETs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATALOGO_PRODUCTO", Storage="_CATALOGO", ThisKey="tipo", OtherKey="idCatalogo", IsForeignKey=true)]
		public CATALOGO CATALOGO
		{
			get
			{
				return this._CATALOGO.Entity;
			}
			set
			{
				CATALOGO previousValue = this._CATALOGO.Entity;
				if (((previousValue != value) 
							|| (this._CATALOGO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATALOGO.Entity = null;
						previousValue.PRODUCTOs.Remove(this);
					}
					this._CATALOGO.Entity = value;
					if ((value != null))
					{
						value.PRODUCTOs.Add(this);
						this._tipo = value.idCatalogo;
					}
					else
					{
						this._tipo = default(int);
					}
					this.SendPropertyChanged("CATALOGO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONFIG_PROMOCIONs(CONFIG_PROMOCION entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO1 = this;
		}
		
		private void detach_CONFIG_PROMOCIONs(CONFIG_PROMOCION entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO1 = null;
		}
		
		private void attach_TICKETs(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO1 = this;
		}
		
		private void detach_TICKETs(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROMOCION")]
	public partial class PROMOCION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPromocion;
		
		private string _nombre;
		
		private System.DateTime _desde;
		
		private System.DateTime _hatas;
		
		private decimal _precio_venta;
		
		private bool _activo;
		
		private EntitySet<CONFIG_PROMOCION> _CONFIG_PROMOCIONs;
		
		private EntitySet<TICKET> _TICKETs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPromocionChanging(string value);
    partial void OnidPromocionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndesdeChanging(System.DateTime value);
    partial void OndesdeChanged();
    partial void OnhatasChanging(System.DateTime value);
    partial void OnhatasChanged();
    partial void Onprecio_ventaChanging(decimal value);
    partial void Onprecio_ventaChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public PROMOCION()
		{
			this._CONFIG_PROMOCIONs = new EntitySet<CONFIG_PROMOCION>(new Action<CONFIG_PROMOCION>(this.attach_CONFIG_PROMOCIONs), new Action<CONFIG_PROMOCION>(this.detach_CONFIG_PROMOCIONs));
			this._TICKETs = new EntitySet<TICKET>(new Action<TICKET>(this.attach_TICKETs), new Action<TICKET>(this.detach_TICKETs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPromocion", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPromocion
		{
			get
			{
				return this._idPromocion;
			}
			set
			{
				if ((this._idPromocion != value))
				{
					this.OnidPromocionChanging(value);
					this.SendPropertyChanging();
					this._idPromocion = value;
					this.SendPropertyChanged("idPromocion");
					this.OnidPromocionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desde", DbType="Date NOT NULL")]
		public System.DateTime desde
		{
			get
			{
				return this._desde;
			}
			set
			{
				if ((this._desde != value))
				{
					this.OndesdeChanging(value);
					this.SendPropertyChanging();
					this._desde = value;
					this.SendPropertyChanged("desde");
					this.OndesdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hatas", DbType="Date NOT NULL")]
		public System.DateTime hatas
		{
			get
			{
				return this._hatas;
			}
			set
			{
				if ((this._hatas != value))
				{
					this.OnhatasChanging(value);
					this.SendPropertyChanging();
					this._hatas = value;
					this.SendPropertyChanged("hatas");
					this.OnhatasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Money NOT NULL")]
		public decimal precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROMOCION_CONFIG_PROMOCION", Storage="_CONFIG_PROMOCIONs", ThisKey="idPromocion", OtherKey="promocion")]
		public EntitySet<CONFIG_PROMOCION> CONFIG_PROMOCIONs
		{
			get
			{
				return this._CONFIG_PROMOCIONs;
			}
			set
			{
				this._CONFIG_PROMOCIONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROMOCION_TICKET", Storage="_TICKETs", ThisKey="idPromocion", OtherKey="promocion")]
		public EntitySet<TICKET> TICKETs
		{
			get
			{
				return this._TICKETs;
			}
			set
			{
				this._TICKETs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONFIG_PROMOCIONs(CONFIG_PROMOCION entity)
		{
			this.SendPropertyChanging();
			entity.PROMOCION1 = this;
		}
		
		private void detach_CONFIG_PROMOCIONs(CONFIG_PROMOCION entity)
		{
			this.SendPropertyChanging();
			entity.PROMOCION1 = null;
		}
		
		private void attach_TICKETs(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.PROMOCION1 = this;
		}
		
		private void detach_TICKETs(TICKET entity)
		{
			this.SendPropertyChanging();
			entity.PROMOCION1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ROL")]
	public partial class ROL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRol;
		
		private string _nombre;
		
		private string _decripcion;
		
		private System.Nullable<bool> _activo;
		
		private EntitySet<ROL_MENU> _ROL_MENUs;
		
		private EntitySet<USUARIO> _USUARIOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRolChanging(int value);
    partial void OnidRolChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndecripcionChanging(string value);
    partial void OndecripcionChanged();
    partial void OnactivoChanging(System.Nullable<bool> value);
    partial void OnactivoChanged();
    #endregion
		
		public ROL()
		{
			this._ROL_MENUs = new EntitySet<ROL_MENU>(new Action<ROL_MENU>(this.attach_ROL_MENUs), new Action<ROL_MENU>(this.detach_ROL_MENUs));
			this._USUARIOs = new EntitySet<USUARIO>(new Action<USUARIO>(this.attach_USUARIOs), new Action<USUARIO>(this.detach_USUARIOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					this.OnidRolChanging(value);
					this.SendPropertyChanging();
					this._idRol = value;
					this.SendPropertyChanged("idRol");
					this.OnidRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decripcion", DbType="VarChar(140)")]
		public string decripcion
		{
			get
			{
				return this._decripcion;
			}
			set
			{
				if ((this._decripcion != value))
				{
					this.OndecripcionChanging(value);
					this.SendPropertyChanging();
					this._decripcion = value;
					this.SendPropertyChanged("decripcion");
					this.OndecripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit")]
		public System.Nullable<bool> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROL_ROL_MENU", Storage="_ROL_MENUs", ThisKey="idRol", OtherKey="rol")]
		public EntitySet<ROL_MENU> ROL_MENUs
		{
			get
			{
				return this._ROL_MENUs;
			}
			set
			{
				this._ROL_MENUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROL_USUARIO", Storage="_USUARIOs", ThisKey="idRol", OtherKey="rol")]
		public EntitySet<USUARIO> USUARIOs
		{
			get
			{
				return this._USUARIOs;
			}
			set
			{
				this._USUARIOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ROL_MENUs(ROL_MENU entity)
		{
			this.SendPropertyChanging();
			entity.ROL1 = this;
		}
		
		private void detach_ROL_MENUs(ROL_MENU entity)
		{
			this.SendPropertyChanging();
			entity.ROL1 = null;
		}
		
		private void attach_USUARIOs(USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.ROL1 = this;
		}
		
		private void detach_USUARIOs(USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.ROL1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ROL_MENU")]
	public partial class ROL_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rol;
		
		private int _menu;
		
		private System.Nullable<bool> _activo;
		
		private EntityRef<MENU> _MENU1;
		
		private EntityRef<ROL> _ROL1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrolChanging(int value);
    partial void OnrolChanged();
    partial void OnmenuChanging(int value);
    partial void OnmenuChanged();
    partial void OnactivoChanging(System.Nullable<bool> value);
    partial void OnactivoChanged();
    #endregion
		
		public ROL_MENU()
		{
			this._MENU1 = default(EntityRef<MENU>);
			this._ROL1 = default(EntityRef<ROL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					if (this._ROL1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int menu
		{
			get
			{
				return this._menu;
			}
			set
			{
				if ((this._menu != value))
				{
					if (this._MENU1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmenuChanging(value);
					this.SendPropertyChanging();
					this._menu = value;
					this.SendPropertyChanged("menu");
					this.OnmenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit")]
		public System.Nullable<bool> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_ROL_MENU", Storage="_MENU1", ThisKey="menu", OtherKey="idMenu", IsForeignKey=true)]
		public MENU MENU1
		{
			get
			{
				return this._MENU1.Entity;
			}
			set
			{
				MENU previousValue = this._MENU1.Entity;
				if (((previousValue != value) 
							|| (this._MENU1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MENU1.Entity = null;
						previousValue.ROL_MENUs.Remove(this);
					}
					this._MENU1.Entity = value;
					if ((value != null))
					{
						value.ROL_MENUs.Add(this);
						this._menu = value.idMenu;
					}
					else
					{
						this._menu = default(int);
					}
					this.SendPropertyChanged("MENU1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROL_ROL_MENU", Storage="_ROL1", ThisKey="rol", OtherKey="idRol", IsForeignKey=true)]
		public ROL ROL1
		{
			get
			{
				return this._ROL1.Entity;
			}
			set
			{
				ROL previousValue = this._ROL1.Entity;
				if (((previousValue != value) 
							|| (this._ROL1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ROL1.Entity = null;
						previousValue.ROL_MENUs.Remove(this);
					}
					this._ROL1.Entity = value;
					if ((value != null))
					{
						value.ROL_MENUs.Add(this);
						this._rol = value.idRol;
					}
					else
					{
						this._rol = default(int);
					}
					this.SendPropertyChanged("ROL1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TICKET")]
	public partial class TICKET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTicket;
		
		private System.DateTime _fecha;
		
		private string _usuario;
		
		private System.Nullable<int> _producto;
		
		private string _promocion;
		
		private EntityRef<PRODUCTO> _PRODUCTO1;
		
		private EntityRef<PROMOCION> _PROMOCION1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTicketChanging(int value);
    partial void OnidTicketChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnproductoChanging(System.Nullable<int> value);
    partial void OnproductoChanged();
    partial void OnpromocionChanging(string value);
    partial void OnpromocionChanged();
    #endregion
		
		public TICKET()
		{
			this._PRODUCTO1 = default(EntityRef<PRODUCTO>);
			this._PROMOCION1 = default(EntityRef<PROMOCION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTicket", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTicket
		{
			get
			{
				return this._idTicket;
			}
			set
			{
				if ((this._idTicket != value))
				{
					this.OnidTicketChanging(value);
					this.SendPropertyChanging();
					this._idTicket = value;
					this.SendPropertyChanged("idTicket");
					this.OnidTicketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="Int")]
		public System.Nullable<int> producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					if (this._PRODUCTO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductoChanging(value);
					this.SendPropertyChanging();
					this._producto = value;
					this.SendPropertyChanged("producto");
					this.OnproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_promocion", DbType="VarChar(30)")]
		public string promocion
		{
			get
			{
				return this._promocion;
			}
			set
			{
				if ((this._promocion != value))
				{
					if (this._PROMOCION1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpromocionChanging(value);
					this.SendPropertyChanging();
					this._promocion = value;
					this.SendPropertyChanged("promocion");
					this.OnpromocionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_TICKET", Storage="_PRODUCTO1", ThisKey="producto", OtherKey="idProdcuto", IsForeignKey=true)]
		public PRODUCTO PRODUCTO1
		{
			get
			{
				return this._PRODUCTO1.Entity;
			}
			set
			{
				PRODUCTO previousValue = this._PRODUCTO1.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCTO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCTO1.Entity = null;
						previousValue.TICKETs.Remove(this);
					}
					this._PRODUCTO1.Entity = value;
					if ((value != null))
					{
						value.TICKETs.Add(this);
						this._producto = value.idProdcuto;
					}
					else
					{
						this._producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("PRODUCTO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROMOCION_TICKET", Storage="_PROMOCION1", ThisKey="promocion", OtherKey="idPromocion", IsForeignKey=true)]
		public PROMOCION PROMOCION1
		{
			get
			{
				return this._PROMOCION1.Entity;
			}
			set
			{
				PROMOCION previousValue = this._PROMOCION1.Entity;
				if (((previousValue != value) 
							|| (this._PROMOCION1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROMOCION1.Entity = null;
						previousValue.TICKETs.Remove(this);
					}
					this._PROMOCION1.Entity = value;
					if ((value != null))
					{
						value.TICKETs.Add(this);
						this._promocion = value.idPromocion;
					}
					else
					{
						this._promocion = default(string);
					}
					this.SendPropertyChanged("PROMOCION1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	

	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nombre;
		
		private string _usuario1;
		
		private string _clave;
		
		private System.Nullable<char> _sexo;
		
		private string _DUI;
		
		private System.Nullable<int> _rol;
		
		private System.Nullable<bool> _activo;
		
		private EntityRef<ROL> _ROL1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onusuario1Changing(string value);
    partial void Onusuario1Changed();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnsexoChanging(System.Nullable<char> value);
    partial void OnsexoChanged();
    partial void OnDUIChanging(string value);
    partial void OnDUIChanged();
    partial void OnrolChanging(System.Nullable<int> value);
    partial void OnrolChanged();
    partial void OnactivoChanging(System.Nullable<bool> value);
    partial void OnactivoChanged();
    #endregion
		
		public USUARIO()
		{
			this._ROL1 = default(EntityRef<ROL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(70)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usuario", Storage="_usuario1", DbType="VarChar(20)")]
		public string usuario1
		{
			get
			{
				return this._usuario1;
			}
			set
			{
				if ((this._usuario1 != value))
				{
					this.Onusuario1Changing(value);
					this.SendPropertyChanging();
					this._usuario1 = value;
					this.SendPropertyChanged("usuario1");
					this.Onusuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(20)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1)")]
		public System.Nullable<char> sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DUI
		{
			get
			{
				return this._DUI;
			}
			set
			{
				if ((this._DUI != value))
				{
					this.OnDUIChanging(value);
					this.SendPropertyChanging();
					this._DUI = value;
					this.SendPropertyChanged("DUI");
					this.OnDUIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="Int")]
		public System.Nullable<int> rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					if (this._ROL1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit")]
		public System.Nullable<bool> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROL_USUARIO", Storage="_ROL1", ThisKey="rol", OtherKey="idRol", IsForeignKey=true)]
		public ROL ROL1
		{
			get
			{
				return this._ROL1.Entity;
			}
			set
			{
				ROL previousValue = this._ROL1.Entity;
				if (((previousValue != value) 
							|| (this._ROL1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ROL1.Entity = null;
						previousValue.USUARIOs.Remove(this);
					}
					this._ROL1.Entity = value;
					if ((value != null))
					{
						value.USUARIOs.Add(this);
						this._rol = value.idRol;
					}
					else
					{
						this._rol = default(Nullable<int>);
					}
					this.SendPropertyChanged("ROL1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
